### ISSUE TITLE
Need a better matching strategy

### ISSUE THREAD

**Issue by NickLarsenNZ** [NickLarsenNZ/mock-http-response#5]
http.HandlerFunc(path, func) are very path oriented.

The ResponderConfig should generate a map of them with the key being the path. Then the wrapper HandlerFunc can search for the appropriate Responder by matching methods, headers, and body.

Probably need to rethink the `ResponderConfig.FindMatchingResponder(...)` method. Or maybe even the Yaml structure.

**Comment by NickLarsenNZ** [comment]
A lot has changed since the above comment, but this is still a problem.

For example:

```yaml
responders:
# If this appears first
- when:
    http:
      method: GET
      path: /things
    headers:
      Content-Type: text/plain
  then:
    http:
      status: 200
    headers:
      Content-Type: text/plain
    body: |
      thing1
      thing2
      thing3

# But we are trying to match this one
- when:
    http:
      method: GET
      path: /things
    headers:
      Content-Type: application/json
  then:
    http:
      status: 200
    headers:
      Content-Type: application/json
    body: |
      [
          {"Name": "thing1"},
          {"Name": "thing2"},
          {"Name": "thing3"},
      ]

```

Then we get this output:
```
go test ./test/
--- FAIL: TestUtility (0.00s)
    e2e_test.go:57: 
        expected body: '[
            {"Name": "thing1"},
            {"Name": "thing2"},
            {"Name": "thing3"},
        ]'
        actual body: 'thing1
        thing2
        thing3'
FAIL
FAIL    github.com/nicklarsennz/mock-http-response/test 0.003s
FAIL
```
